# Generated by Django 2.2.3 on 2019-09-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
